---
run:
  concurrency: 6
  timeout: 5m
  build-tags:
    - testtools

issues:
  exclude-rules:
    - linters:
        - goerr113
      text: do not define dynamic errors, use wrapped static errors instead
linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - decorder
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - copyloopvar
    - forcetypeassert
    - gci
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - err113
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - mnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - grouper
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagliatelle
    - usetesting
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
    # - contextcheck
    # - cyclop
    # - exhaustivestruct
    # - forbidigo
    # - funlen
    # - gochecknoglobals
    # - ireturn
    # - maintidx
    # - nlreturn
    # - testpackage
    # - varnamelen
    # - wrapcheck
    # - wsl
linters-settings:
  gocognit:
    min-complexity: 40
  nestif:
    min-complexity: 15
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/metal-toolbox)
  errcheck:
    check-type-assertions: true
    check-blank: true
  godox:
    keywords:
      - BUG
      - FIXME
      - HACK
  gocritic:
    enabled-checks:
      # Diagnostic
      - badLock
      - badRegexp
      - badSorting
      - builtinShadowDecl
      - commentedOutCode
      - deferInLoop
      - dynamicFmtString
      - emptyDecl
      - evalOrder
      - externalErrorReassign
      - filepathJoin
      - nilValReturn
      - regexpPattern
      - returnAfterHttpError
      - sloppyReassign
      - sortSlice
      - sprintfQuotedString
      - sqlQuery
      - syncMapLoadAndDelete
      - truncateCmp
      - unnecessaryDefer
      - weakCond

      # Performance
      - appendCombine
      - equalFold
      - hugeParam
      - indexAlloc
      - preferDecodeRune
      - preferFprint
      - preferStringWriter
      - preferWriteByte
      - rangeExprCopy
      - rangeValCopy
      - sliceClear
      - stringXbytes

      # Style
      - boolExprSimplify
      - commentedOutImport
      - deferUnlambda
      - docStub
      - dupImport
      - emptyFallthrough
      - emptyStringTest
      - exposedSyncMutex
      - hexLiteral
      - httpNoBody
      - methodExprCall
      - octalLiteral
      - preferFilepathJoin
      - redundantSprint
      - regexpSimplify
      - ruleguard
      - stringConcatSimplify
      - timeExprSimplify
      - tooManyResultsChecker
      - typeAssertChain
      - typeDefFirst
      - unlabelStmt
      - whyNoLint
      - yodaStyleExpr

      # Opinionated
      - builtinShadow
      - importShadow
      - initClause
      - nestingReduce
      - paramTypeCombine
      - ptrToRefParam
      - typeUnparen
      - unnamedResult
      - unnecessaryBlock
