---
name: Linting and Test

# Run for all pushes to main and pull requests when Go or YAML files change
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  golangci:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.45
          args: --timeout=5m

      - name: Run go tests and generate coverage report
        run: make coverge

      - name: Upload coverage report
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.out
          flags: unittests
          name: codecov-umbrella
