---
name: test

# Run for all pushes to main and pull requests when Go or YAML files change
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - name: Run golangci-lint
        run: make lint

      - name: Run go tests and generate coverage report
        run: make coverage

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.out
          flags: unittests
          name: codecov-umbrella

  build-image:
    name: build-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./images/audittail/Dockerfile
          push: false
          tags: gchr.io/metal-toolbox/audittail:latest

      - name: Scan image
        id: scan
        uses: anchore/scan-action@v3
        with:
          image: gchr.io/metal-toolbox/audittail:latest
          acs-report-enable: true

      - name: upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
      
      - name: Inspect action SARIF report
        run: cat ${{ steps.scan.outputs.sarif }}

  security-scan-trivy:
    name: sec-scan-trivy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'HIGH,CRITICAL'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'

  security-scan-anchore:
    name: sec-scan-anchore
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      
      - name: Scan current project
        id: codescan
        uses: anchore/scan-action@v3
        with:
          path: "."
          severity-cutoff: high
          acs-report-enable: true

      - name: upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@v1
        if: ${{ always() }}
        with:
          sarif_file: ${{ steps.codescan.outputs.sarif }}