---
name: test

# Run for all pushes to main and pull requests when Go or YAML files change
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'

      - name: Run golangci-lint
        run: make lint

      - name: Run go tests and generate coverage report
        run: make coverage

      - name: Upload coverage report
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.out
          flags: unittests
          name: codecov-umbrella

  build-image:
    name: build-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./images/audittail/Containerfile
          push: false
          tags: gchr.io/metal-toolbox/audittail:latest

      - name: Scan image
        id: scan
        uses: anchore/scan-action@v3
        with:
          image: gchr.io/metal-toolbox/audittail:latest
          acs-report-enable: true

      - name: upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
      
      - name: Inspect action SARIF report
        run: cat ${{ steps.scan.outputs.sarif }}